version: '3.7'

services:
  backend-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/money-book/src
    ports:
      - 3000:3000

  database-server:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'money-book'
      MYSQL_ROOT_PASSWORD: '2222'
      TZ: 'Asia/Seoul'
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+09:00',
      ]
    ports:
      - 3306:3306
